set dotenv-load
format:
	gofumpt -l -w .
	goimports-reviser -rm-unused -set-alias ./...
	golines -w -m 120 .

gqlgen-gen:
	go run github.com/99designs/gqlgen generate

# build -> build application
build:
	go build -o server .

# run -> application
run:
	./server

# dev -> run build then run it
dev: 
	watchexec -r -c -e go -- just build run

# test -> testing
test:
  go install github.com/bitfield/gotestdox/cmd/gotestdox@latest

# health -> Hit Health Check Endpoint
health:
	curl -s http://localhost:8000/healthz | jq

# migrate-create -> create migration
migrate-create NAME:
	migrate create -ext sql -dir ./migrations -seq {{NAME}}

# migrate-up -> up migration
migrate-up:
	echo $DATABASE_URL
	migrate -path ./migrations -database "$DATABASE_URL" up

# migrate-down -> reset migration
migrate-down:
	migrate -path ./migrations -database "$DATABASE_URL" down