// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CreatePatientInput struct {
	FullName         string                 `json:"full_name"`
	DateOfBirth      time.Time              `json:"date_of_birth"`
	Gender           Gender                 `json:"gender"`
	Phone            *string                `json:"phone"`
	Email            *string                `json:"email"`
	Address          *string                `json:"address"`
	EmergencyContact *EmergencyContactInput `json:"emergency_contact"`
}

type CreateStaffInput struct {
	UserID         uuid.UUID `json:"user_id"`
	FullName       string    `json:"full_name"`
	Specialization *string   `json:"specialization"`
	LicenseNo      *string   `json:"license_no"`
	Phone          *string   `json:"phone"`
}

type CreateTreatmentSessionInput struct {
	PatientID   uuid.UUID `json:"patient_id"`
	StaffID     uuid.UUID `json:"staff_id"`
	SessionDate time.Time `json:"session_date"`
}

type CreateTreatmentSessionReportInput struct {
	SessionID            uuid.UUID `json:"session_id"`
	Anamnesis            *string   `json:"anamnesis"`
	MechanismOfInjury    *string   `json:"mechanism_of_injury"`
	ActualCondition      *string   `json:"actual_condition"`
	Examination          *string   `json:"examination"`
	Diagnosis            *string   `json:"diagnosis"`
	Intervention         *string   `json:"intervention"`
	PlanningAndEducation *string   `json:"planning_and_education"`
}

type CreateUserInput struct {
	Email    string   `json:"email"`
	Password string   `json:"password"`
	Role     UserRole `json:"role"`
}

type EmergencyContact struct {
	Name     string `json:"name"`
	Phone    string `json:"phone"`
	Relation string `json:"relation"`
}

type EmergencyContactInput struct {
	Name     string `json:"name"`
	Phone    string `json:"phone"`
	Relation string `json:"relation"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Patient struct {
	ID                uuid.UUID           `json:"id"`
	MedicalRecordNo   string              `json:"medical_record_no"`
	FullName          string              `json:"full_name"`
	DateOfBirth       time.Time           `json:"date_of_birth"`
	Gender            Gender              `json:"gender"`
	Phone             *string             `json:"phone"`
	Email             *string             `json:"email"`
	Address           *string             `json:"address"`
	EmergencyContact  *EmergencyContact   `json:"emergency_contact"`
	CreatedAt         time.Time           `json:"created_at"`
	UpdatedAt         time.Time           `json:"updated_at"`
	TreatmentSessions []*TreatmentSession `json:"treatment_sessions"`
}

type PatientConnection struct {
	Nodes      []*Patient `json:"nodes"`
	TotalCount int32      `json:"total_count"`
}

type Pong struct {
	Success bool `json:"success"`
}

type Query struct {
}

type ReportFilter struct {
	DateFrom *time.Time `json:"date_from"`
	DateTo   *time.Time `json:"date_to"`
	// Matches patient name, session number, or report text fields.
	Search *string `json:"search"`
}

type SessionFilter struct {
	PatientID *uuid.UUID     `json:"patient_id"`
	StaffID   *uuid.UUID     `json:"staff_id"`
	Status    *SessionStatus `json:"status"`
	DateFrom  *time.Time     `json:"date_from"`
	DateTo    *time.Time     `json:"date_to"`
	// Matches patient name, therapist name, or session number.
	Search *string `json:"search"`
}

type Staff struct {
	ID                uuid.UUID           `json:"id"`
	UserID            uuid.UUID           `json:"user_id"`
	FullName          string              `json:"full_name"`
	Specialization    *string             `json:"specialization"`
	LicenseNo         *string             `json:"license_no"`
	Phone             *string             `json:"phone"`
	CreatedAt         time.Time           `json:"created_at"`
	UpdatedAt         time.Time           `json:"updated_at"`
	User              *User               `json:"user"`
	TreatmentSessions []*TreatmentSession `json:"treatment_sessions"`
}

type StaffConnection struct {
	Nodes      []*Staff `json:"nodes"`
	TotalCount int32    `json:"total_count"`
}

type TreatmentSession struct {
	ID          uuid.UUID               `json:"id"`
	PatientID   uuid.UUID               `json:"patient_id"`
	StaffID     uuid.UUID               `json:"staff_id"`
	SessionDate time.Time               `json:"session_date"`
	SessionNo   int32                   `json:"session_no"`
	Status      SessionStatus           `json:"status"`
	Note        *string                 `json:"note"`
	CreatedAt   time.Time               `json:"created_at"`
	UpdatedAt   time.Time               `json:"updated_at"`
	Patient     *Patient                `json:"patient"`
	Staff       *Staff                  `json:"staff"`
	Report      *TreatmentSessionReport `json:"report"`
}

type TreatmentSessionConnection struct {
	Nodes      []*TreatmentSession `json:"nodes"`
	TotalCount int32               `json:"total_count"`
}

type TreatmentSessionReport struct {
	ID                   uuid.UUID         `json:"id"`
	SessionID            uuid.UUID         `json:"session_id"`
	Anamnesis            *string           `json:"anamnesis"`
	MechanismOfInjury    *string           `json:"mechanism_of_injury"`
	ActualCondition      *string           `json:"actual_condition"`
	Examination          *string           `json:"examination"`
	Diagnosis            *string           `json:"diagnosis"`
	Intervention         *string           `json:"intervention"`
	PlanningAndEducation *string           `json:"planning_and_education"`
	CreatedAt            time.Time         `json:"created_at"`
	UpdatedAt            time.Time         `json:"updated_at"`
	TreatmentSession     *TreatmentSession `json:"treatment_session"`
}

type TreatmentSessionReportConnection struct {
	Nodes      []*TreatmentSessionReport `json:"nodes"`
	TotalCount int32                     `json:"total_count"`
}

type UpdatePatientInput struct {
	FullName         *string                `json:"full_name"`
	Phone            *string                `json:"phone"`
	Email            *string                `json:"email"`
	Address          *string                `json:"address"`
	EmergencyContact *EmergencyContactInput `json:"emergency_contact"`
}

type UpdateStaffInput struct {
	FullName       *string `json:"full_name"`
	Specialization *string `json:"specialization"`
	LicenseNo      *string `json:"license_no"`
	Phone          *string `json:"phone"`
}

type UpdateTreatmentSessionReportInput struct {
	Anamnesis            *string `json:"anamnesis"`
	MechanismOfInjury    *string `json:"mechanism_of_injury"`
	ActualCondition      *string `json:"actual_condition"`
	Examination          *string `json:"examination"`
	Diagnosis            *string `json:"diagnosis"`
	Intervention         *string `json:"intervention"`
	PlanningAndEducation *string `json:"planning_and_education"`
}

type UpdateTreatmentSessionStatusInput struct {
	Status SessionStatus `json:"status"`
}

type UpdateUserInput struct {
	Email    *string   `json:"email"`
	Password *string   `json:"password"`
	Role     *UserRole `json:"role"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Role      UserRole  `json:"role"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Staff     *Staff    `json:"staff"`
}

type Gender string

const (
	GenderMale   Gender = "MALE"
	GenderFemale Gender = "FEMALE"
)

var AllGender = []Gender{
	GenderMale,
	GenderFemale,
}

func (e Gender) IsValid() bool {
	switch e {
	case GenderMale, GenderFemale:
		return true
	}
	return false
}

func (e Gender) String() string {
	return string(e)
}

func (e *Gender) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Gender(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Gender", str)
	}
	return nil
}

func (e Gender) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Gender) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Gender) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PatientSortField string

const (
	PatientSortFieldFullName        PatientSortField = "FULL_NAME"
	PatientSortFieldMedicalRecordNo PatientSortField = "MEDICAL_RECORD_NO"
	PatientSortFieldDateOfBirth     PatientSortField = "DATE_OF_BIRTH"
	PatientSortFieldGender          PatientSortField = "GENDER"
	PatientSortFieldCreatedAt       PatientSortField = "CREATED_AT"
)

var AllPatientSortField = []PatientSortField{
	PatientSortFieldFullName,
	PatientSortFieldMedicalRecordNo,
	PatientSortFieldDateOfBirth,
	PatientSortFieldGender,
	PatientSortFieldCreatedAt,
}

func (e PatientSortField) IsValid() bool {
	switch e {
	case PatientSortFieldFullName, PatientSortFieldMedicalRecordNo, PatientSortFieldDateOfBirth, PatientSortFieldGender, PatientSortFieldCreatedAt:
		return true
	}
	return false
}

func (e PatientSortField) String() string {
	return string(e)
}

func (e *PatientSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PatientSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PatientSortField", str)
	}
	return nil
}

func (e PatientSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PatientSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PatientSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SessionStatus string

const (
	SessionStatusScheduled  SessionStatus = "SCHEDULED"
	SessionStatusInProgress SessionStatus = "IN_PROGRESS"
	SessionStatusCompleted  SessionStatus = "COMPLETED"
	SessionStatusCancelled  SessionStatus = "CANCELLED"
)

var AllSessionStatus = []SessionStatus{
	SessionStatusScheduled,
	SessionStatusInProgress,
	SessionStatusCompleted,
	SessionStatusCancelled,
}

func (e SessionStatus) IsValid() bool {
	switch e {
	case SessionStatusScheduled, SessionStatusInProgress, SessionStatusCompleted, SessionStatusCancelled:
		return true
	}
	return false
}

func (e SessionStatus) String() string {
	return string(e)
}

func (e *SessionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SessionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SessionStatus", str)
	}
	return nil
}

func (e SessionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SessionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SessionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortOrder string

const (
	SortOrderAsc  SortOrder = "ASC"
	SortOrderDesc SortOrder = "DESC"
)

var AllSortOrder = []SortOrder{
	SortOrderAsc,
	SortOrderDesc,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderAsc, SortOrderDesc:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type StaffSortField string

const (
	StaffSortFieldFullName       StaffSortField = "FULL_NAME"
	StaffSortFieldEmail          StaffSortField = "EMAIL"
	StaffSortFieldLicenseNo      StaffSortField = "LICENSE_NO"
	StaffSortFieldPhone          StaffSortField = "PHONE"
	StaffSortFieldSpecialization StaffSortField = "SPECIALIZATION"
	StaffSortFieldCreatedAt      StaffSortField = "CREATED_AT"
)

var AllStaffSortField = []StaffSortField{
	StaffSortFieldFullName,
	StaffSortFieldEmail,
	StaffSortFieldLicenseNo,
	StaffSortFieldPhone,
	StaffSortFieldSpecialization,
	StaffSortFieldCreatedAt,
}

func (e StaffSortField) IsValid() bool {
	switch e {
	case StaffSortFieldFullName, StaffSortFieldEmail, StaffSortFieldLicenseNo, StaffSortFieldPhone, StaffSortFieldSpecialization, StaffSortFieldCreatedAt:
		return true
	}
	return false
}

func (e StaffSortField) String() string {
	return string(e)
}

func (e *StaffSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StaffSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StaffSortField", str)
	}
	return nil
}

func (e StaffSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *StaffSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e StaffSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TreatmentSessionReportSortField string

const (
	TreatmentSessionReportSortFieldCreatedAt   TreatmentSessionReportSortField = "CREATED_AT"
	TreatmentSessionReportSortFieldSessionDate TreatmentSessionReportSortField = "SESSION_DATE"
	TreatmentSessionReportSortFieldPatientName TreatmentSessionReportSortField = "PATIENT_NAME"
	TreatmentSessionReportSortFieldDiagnosis   TreatmentSessionReportSortField = "DIAGNOSIS"
)

var AllTreatmentSessionReportSortField = []TreatmentSessionReportSortField{
	TreatmentSessionReportSortFieldCreatedAt,
	TreatmentSessionReportSortFieldSessionDate,
	TreatmentSessionReportSortFieldPatientName,
	TreatmentSessionReportSortFieldDiagnosis,
}

func (e TreatmentSessionReportSortField) IsValid() bool {
	switch e {
	case TreatmentSessionReportSortFieldCreatedAt, TreatmentSessionReportSortFieldSessionDate, TreatmentSessionReportSortFieldPatientName, TreatmentSessionReportSortFieldDiagnosis:
		return true
	}
	return false
}

func (e TreatmentSessionReportSortField) String() string {
	return string(e)
}

func (e *TreatmentSessionReportSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TreatmentSessionReportSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TreatmentSessionReportSortField", str)
	}
	return nil
}

func (e TreatmentSessionReportSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TreatmentSessionReportSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TreatmentSessionReportSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TreatmentSessionSortField string

const (
	TreatmentSessionSortFieldSessionDate TreatmentSessionSortField = "SESSION_DATE"
	TreatmentSessionSortFieldSessionNo   TreatmentSessionSortField = "SESSION_NO"
	TreatmentSessionSortFieldStatus      TreatmentSessionSortField = "STATUS"
	TreatmentSessionSortFieldCreatedAt   TreatmentSessionSortField = "CREATED_AT"
	TreatmentSessionSortFieldPatientName TreatmentSessionSortField = "PATIENT_NAME"
	TreatmentSessionSortFieldStaffName   TreatmentSessionSortField = "STAFF_NAME"
)

var AllTreatmentSessionSortField = []TreatmentSessionSortField{
	TreatmentSessionSortFieldSessionDate,
	TreatmentSessionSortFieldSessionNo,
	TreatmentSessionSortFieldStatus,
	TreatmentSessionSortFieldCreatedAt,
	TreatmentSessionSortFieldPatientName,
	TreatmentSessionSortFieldStaffName,
}

func (e TreatmentSessionSortField) IsValid() bool {
	switch e {
	case TreatmentSessionSortFieldSessionDate, TreatmentSessionSortFieldSessionNo, TreatmentSessionSortFieldStatus, TreatmentSessionSortFieldCreatedAt, TreatmentSessionSortFieldPatientName, TreatmentSessionSortFieldStaffName:
		return true
	}
	return false
}

func (e TreatmentSessionSortField) String() string {
	return string(e)
}

func (e *TreatmentSessionSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TreatmentSessionSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TreatmentSessionSortField", str)
	}
	return nil
}

func (e TreatmentSessionSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TreatmentSessionSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TreatmentSessionSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRoleAdmin        UserRole = "ADMIN"
	UserRoleTherapist    UserRole = "THERAPIST"
	UserRoleReceptionist UserRole = "RECEPTIONIST"
)

var AllUserRole = []UserRole{
	UserRoleAdmin,
	UserRoleTherapist,
	UserRoleReceptionist,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleAdmin, UserRoleTherapist, UserRoleReceptionist:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
