// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type Appointment struct {
	ID             uuid.UUID         `json:"id"`
	PatientID      uuid.UUID         `json:"patientId"`
	StaffID        uuid.UUID         `json:"staffId"`
	ScheduledAt    time.Time         `json:"scheduledAt"`
	DurationMin    int32             `json:"durationMin"`
	Status         AppointmentStatus `json:"status"`
	ChiefComplaint *string           `json:"chiefComplaint,omitempty"`
	Notes          *string           `json:"notes,omitempty"`
	CreatedAt      time.Time         `json:"createdAt"`
	UpdatedAt      time.Time         `json:"updatedAt"`
	Patient        *Patient          `json:"patient"`
	Staff          *Staff            `json:"staff"`
	Session        *TreatmentSession `json:"session,omitempty"`
}

type AppointmentConnection struct {
	Nodes      []*Appointment `json:"nodes"`
	TotalCount int32          `json:"totalCount"`
}

type AppointmentFilter struct {
	PatientID *uuid.UUID         `json:"patientId,omitempty"`
	StaffID   *uuid.UUID         `json:"staffId,omitempty"`
	Status    *AppointmentStatus `json:"status,omitempty"`
	DateFrom  *time.Time         `json:"dateFrom,omitempty"`
	DateTo    *time.Time         `json:"dateTo,omitempty"`
}

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CreateAppointmentInput struct {
	PatientID      uuid.UUID `json:"patientId"`
	StaffID        uuid.UUID `json:"staffId"`
	ScheduledAt    time.Time `json:"scheduledAt"`
	DurationMin    int32     `json:"durationMin"`
	ChiefComplaint *string   `json:"chiefComplaint,omitempty"`
	Notes          *string   `json:"notes,omitempty"`
}

type CreatePatientInput struct {
	FullName         string                 `json:"fullName"`
	DateOfBirth      time.Time              `json:"dateOfBirth"`
	Gender           Gender                 `json:"gender"`
	Phone            *string                `json:"phone,omitempty"`
	Email            *string                `json:"email,omitempty"`
	Address          *string                `json:"address,omitempty"`
	EmergencyContact *EmergencyContactInput `json:"emergencyContact,omitempty"`
}

type CreateSOAPNoteInput struct {
	SessionID  uuid.UUID    `json:"sessionId"`
	Subjective string       `json:"subjective"`
	Objective  string       `json:"objective"`
	Assessment string       `json:"assessment"`
	Plan       string       `json:"plan"`
	PainScale  *int32       `json:"painScale,omitempty"`
	Vitals     *VitalsInput `json:"vitals,omitempty"`
}

type CreateSessionInput struct {
	AppointmentID *uuid.UUID `json:"appointmentId,omitempty"`
	PatientID     uuid.UUID  `json:"patientId"`
	StaffID       uuid.UUID  `json:"staffId"`
	SessionDate   time.Time  `json:"sessionDate"`
}

type CreateStaffInput struct {
	UserID         uuid.UUID `json:"userId"`
	FullName       string    `json:"fullName"`
	Specialization *string   `json:"specialization,omitempty"`
	LicenseNo      *string   `json:"licenseNo,omitempty"`
	Phone          *string   `json:"phone,omitempty"`
}

type CreateUserInput struct {
	Email    string   `json:"email"`
	Password string   `json:"password"`
	Role     UserRole `json:"role"`
}

type EmergencyContact struct {
	Name     string `json:"name"`
	Phone    string `json:"phone"`
	Relation string `json:"relation"`
}

type EmergencyContactInput struct {
	Name     string `json:"name"`
	Phone    string `json:"phone"`
	Relation string `json:"relation"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Patient struct {
	ID                uuid.UUID           `json:"id"`
	MedicalRecordNo   string              `json:"medicalRecordNo"`
	FullName          string              `json:"fullName"`
	DateOfBirth       time.Time           `json:"dateOfBirth"`
	Gender            Gender              `json:"gender"`
	Phone             *string             `json:"phone,omitempty"`
	Email             *string             `json:"email,omitempty"`
	Address           *string             `json:"address,omitempty"`
	EmergencyContact  *EmergencyContact   `json:"emergencyContact,omitempty"`
	CreatedAt         time.Time           `json:"createdAt"`
	UpdatedAt         time.Time           `json:"updatedAt"`
	Appointments      []*Appointment      `json:"appointments"`
	TreatmentSessions []*TreatmentSession `json:"treatmentSessions"`
}

type PatientConnection struct {
	Nodes      []*Patient `json:"nodes"`
	TotalCount int32      `json:"totalCount"`
}

type Query struct {
}

type SOAPNote struct {
	ID         uuid.UUID         `json:"id"`
	SessionID  uuid.UUID         `json:"sessionId"`
	Subjective string            `json:"subjective"`
	Objective  string            `json:"objective"`
	Assessment string            `json:"assessment"`
	Plan       string            `json:"plan"`
	PainScale  *int32            `json:"painScale,omitempty"`
	Vitals     *Vitals           `json:"vitals,omitempty"`
	CreatedAt  time.Time         `json:"createdAt"`
	UpdatedAt  time.Time         `json:"updatedAt"`
	Session    *TreatmentSession `json:"session"`
}

type SessionFilter struct {
	PatientID *uuid.UUID     `json:"patientId,omitempty"`
	StaffID   *uuid.UUID     `json:"staffId,omitempty"`
	Status    *SessionStatus `json:"status,omitempty"`
	DateFrom  *time.Time     `json:"dateFrom,omitempty"`
	DateTo    *time.Time     `json:"dateTo,omitempty"`
}

type Staff struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"userId"`
	FullName       string         `json:"fullName"`
	Specialization *string        `json:"specialization,omitempty"`
	LicenseNo      *string        `json:"licenseNo,omitempty"`
	Phone          *string        `json:"phone,omitempty"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	User           *User          `json:"user"`
	Appointments   []*Appointment `json:"appointments"`
}

type StaffConnection struct {
	Nodes      []*Staff `json:"nodes"`
	TotalCount int32    `json:"totalCount"`
}

type TreatmentSession struct {
	ID            uuid.UUID     `json:"id"`
	AppointmentID *uuid.UUID    `json:"appointmentId,omitempty"`
	PatientID     uuid.UUID     `json:"patientId"`
	StaffID       uuid.UUID     `json:"staffId"`
	SessionDate   time.Time     `json:"sessionDate"`
	SessionNo     int32         `json:"sessionNo"`
	Status        SessionStatus `json:"status"`
	CreatedAt     time.Time     `json:"createdAt"`
	UpdatedAt     time.Time     `json:"updatedAt"`
	Appointment   *Appointment  `json:"appointment,omitempty"`
	Patient       *Patient      `json:"patient"`
	Staff         *Staff        `json:"staff"`
	SoapNote      *SOAPNote     `json:"soapNote,omitempty"`
}

type TreatmentSessionConnection struct {
	Nodes      []*TreatmentSession `json:"nodes"`
	TotalCount int32               `json:"totalCount"`
}

type UpdateAppointmentStatusInput struct {
	Status AppointmentStatus `json:"status"`
}

type UpdatePatientInput struct {
	FullName         *string                `json:"fullName,omitempty"`
	Phone            *string                `json:"phone,omitempty"`
	Email            *string                `json:"email,omitempty"`
	Address          *string                `json:"address,omitempty"`
	EmergencyContact *EmergencyContactInput `json:"emergencyContact,omitempty"`
}

type UpdateSOAPNoteInput struct {
	Subjective *string      `json:"subjective,omitempty"`
	Objective  *string      `json:"objective,omitempty"`
	Assessment *string      `json:"assessment,omitempty"`
	Plan       *string      `json:"plan,omitempty"`
	PainScale  *int32       `json:"painScale,omitempty"`
	Vitals     *VitalsInput `json:"vitals,omitempty"`
}

type UpdateStaffInput struct {
	FullName       *string `json:"fullName,omitempty"`
	Specialization *string `json:"specialization,omitempty"`
	LicenseNo      *string `json:"licenseNo,omitempty"`
	Phone          *string `json:"phone,omitempty"`
}

type UpdateUserInput struct {
	Email    *string   `json:"email,omitempty"`
	Password *string   `json:"password,omitempty"`
	Role     *UserRole `json:"role,omitempty"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Role      UserRole  `json:"role"`
	IsActive  bool      `json:"isActive"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Staff     *Staff    `json:"staff,omitempty"`
}

type Vitals struct {
	Bp     *string  `json:"bp,omitempty"`
	Hr     *int32   `json:"hr,omitempty"`
	Spo2   *int32   `json:"spo2,omitempty"`
	Temp   *float64 `json:"temp,omitempty"`
	Weight *float64 `json:"weight,omitempty"`
}

type VitalsInput struct {
	Bp     *string  `json:"bp,omitempty"`
	Hr     *int32   `json:"hr,omitempty"`
	Spo2   *int32   `json:"spo2,omitempty"`
	Temp   *float64 `json:"temp,omitempty"`
	Weight *float64 `json:"weight,omitempty"`
}

type AppointmentStatus string

const (
	AppointmentStatusScheduled AppointmentStatus = "SCHEDULED"
	AppointmentStatusConfirmed AppointmentStatus = "CONFIRMED"
	AppointmentStatusCompleted AppointmentStatus = "COMPLETED"
	AppointmentStatusCancelled AppointmentStatus = "CANCELLED"
	AppointmentStatusNoShow    AppointmentStatus = "NO_SHOW"
)

var AllAppointmentStatus = []AppointmentStatus{
	AppointmentStatusScheduled,
	AppointmentStatusConfirmed,
	AppointmentStatusCompleted,
	AppointmentStatusCancelled,
	AppointmentStatusNoShow,
}

func (e AppointmentStatus) IsValid() bool {
	switch e {
	case AppointmentStatusScheduled, AppointmentStatusConfirmed, AppointmentStatusCompleted, AppointmentStatusCancelled, AppointmentStatusNoShow:
		return true
	}
	return false
}

func (e AppointmentStatus) String() string {
	return string(e)
}

func (e *AppointmentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AppointmentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AppointmentStatus", str)
	}
	return nil
}

func (e AppointmentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AppointmentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AppointmentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Gender string

const (
	GenderMale   Gender = "MALE"
	GenderFemale Gender = "FEMALE"
)

var AllGender = []Gender{
	GenderMale,
	GenderFemale,
}

func (e Gender) IsValid() bool {
	switch e {
	case GenderMale, GenderFemale:
		return true
	}
	return false
}

func (e Gender) String() string {
	return string(e)
}

func (e *Gender) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Gender(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Gender", str)
	}
	return nil
}

func (e Gender) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Gender) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Gender) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SessionStatus string

const (
	SessionStatusInProgress SessionStatus = "IN_PROGRESS"
	SessionStatusCompleted  SessionStatus = "COMPLETED"
	SessionStatusCancelled  SessionStatus = "CANCELLED"
)

var AllSessionStatus = []SessionStatus{
	SessionStatusInProgress,
	SessionStatusCompleted,
	SessionStatusCancelled,
}

func (e SessionStatus) IsValid() bool {
	switch e {
	case SessionStatusInProgress, SessionStatusCompleted, SessionStatusCancelled:
		return true
	}
	return false
}

func (e SessionStatus) String() string {
	return string(e)
}

func (e *SessionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SessionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SessionStatus", str)
	}
	return nil
}

func (e SessionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SessionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SessionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRoleAdmin        UserRole = "ADMIN"
	UserRoleTherapist    UserRole = "THERAPIST"
	UserRoleReceptionist UserRole = "RECEPTIONIST"
)

var AllUserRole = []UserRole{
	UserRoleAdmin,
	UserRoleTherapist,
	UserRoleReceptionist,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleAdmin, UserRoleTherapist, UserRoleReceptionist:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
