// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CreatePatientInput struct {
	FullName         string                 `json:"full_name"`
	DateOfBirth      time.Time              `json:"date_of_birth"`
	Gender           Gender                 `json:"gender"`
	Phone            *string                `json:"phone,omitempty"`
	Email            *string                `json:"email,omitempty"`
	Address          *string                `json:"address,omitempty"`
	EmergencyContact *EmergencyContactInput `json:"emergency_contact,omitempty"`
}

type CreateStaffInput struct {
	UserID         uuid.UUID `json:"userId"`
	FullName       string    `json:"full_name"`
	Specialization *string   `json:"specialization,omitempty"`
	LicenseNo      *string   `json:"license_no,omitempty"`
	Phone          *string   `json:"phone,omitempty"`
}

type CreateTreatmentSessionInput struct {
	PatientID   uuid.UUID `json:"patient_id"`
	StaffID     uuid.UUID `json:"staff_id"`
	SessionDate time.Time `json:"session_date"`
}

type CreateTreatmentSessionReportInput struct {
	SessionID            uuid.UUID `json:"session_id"`
	Anamnesis            *string   `json:"anamnesis,omitempty"`
	MechanismOfInjury    *string   `json:"mechanism_of_injury,omitempty"`
	ActualCondition      *string   `json:"actual_condition,omitempty"`
	Examination          *string   `json:"examination,omitempty"`
	Diagnosis            *string   `json:"diagnosis,omitempty"`
	Intervention         *string   `json:"intervention,omitempty"`
	PlanningAndEducation *string   `json:"planning_and_education,omitempty"`
}

type CreateUserInput struct {
	Email    string   `json:"email"`
	Password string   `json:"password"`
	Role     UserRole `json:"role"`
}

type EmergencyContact struct {
	Name     string `json:"name"`
	Phone    string `json:"phone"`
	Relation string `json:"relation"`
}

type EmergencyContactInput struct {
	Name     string `json:"name"`
	Phone    string `json:"phone"`
	Relation string `json:"relation"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Patient struct {
	ID                uuid.UUID           `json:"id"`
	MedicalRecordNo   string              `json:"medical_record_no"`
	FullName          string              `json:"full_name"`
	DateOfBirth       time.Time           `json:"date_of_birth"`
	Gender            Gender              `json:"gender"`
	Phone             *string             `json:"phone,omitempty"`
	Email             *string             `json:"email,omitempty"`
	Address           *string             `json:"address,omitempty"`
	EmergencyContact  *EmergencyContact   `json:"emergency_contact,omitempty"`
	CreatedAt         time.Time           `json:"created_at"`
	UpdatedAt         time.Time           `json:"updated_at"`
	TreatmentSessions []*TreatmentSession `json:"treatment_sessions"`
}

type PatientConnection struct {
	Nodes      []*Patient `json:"nodes"`
	TotalCount int32      `json:"total_count"`
}

type Query struct {
}

type ReportFilter struct {
	DateFrom *time.Time `json:"date_from,omitempty"`
	DateTo   *time.Time `json:"date_to,omitempty"`
}

type SessionFilter struct {
	PatientID *uuid.UUID     `json:"patient_id,omitempty"`
	StaffID   *uuid.UUID     `json:"staff_id,omitempty"`
	Status    *SessionStatus `json:"status,omitempty"`
	DateFrom  *time.Time     `json:"date_from,omitempty"`
	DateTo    *time.Time     `json:"date_to,omitempty"`
}

type Staff struct {
	ID                uuid.UUID           `json:"id"`
	UserID            uuid.UUID           `json:"user_id"`
	FullName          string              `json:"full_name"`
	Specialization    *string             `json:"specialization,omitempty"`
	LicenseNo         *string             `json:"license_no,omitempty"`
	Phone             *string             `json:"phone,omitempty"`
	CreatedAt         time.Time           `json:"created_at"`
	UpdatedAt         time.Time           `json:"updated_at"`
	User              *User               `json:"user"`
	TreatmentSessions []*TreatmentSession `json:"treatment_sessions"`
}

type StaffConnection struct {
	Nodes      []*Staff `json:"nodes"`
	TotalCount int32    `json:"total_count"`
}

type TreatmentSession struct {
	ID          uuid.UUID               `json:"id"`
	PatientID   uuid.UUID               `json:"patient_id"`
	StaffID     uuid.UUID               `json:"staff_id"`
	SessionDate time.Time               `json:"session_date"`
	SessionNo   int32                   `json:"session_no"`
	Status      SessionStatus           `json:"status"`
	Note        *string                 `json:"note,omitempty"`
	CreatedAt   time.Time               `json:"created_at"`
	UpdatedAt   time.Time               `json:"updated_at"`
	Patient     *Patient                `json:"patient"`
	Staff       *Staff                  `json:"staff"`
	Report      *TreatmentSessionReport `json:"report,omitempty"`
}

type TreatmentSessionConnection struct {
	Nodes      []*TreatmentSession `json:"nodes"`
	TotalCount int32               `json:"total_count"`
}

type TreatmentSessionReport struct {
	ID                   uuid.UUID         `json:"id"`
	SessionID            uuid.UUID         `json:"session_id"`
	Anamnesis            *string           `json:"anamnesis,omitempty"`
	MechanismOfInjury    *string           `json:"mechanism_of_injury,omitempty"`
	ActualCondition      *string           `json:"actual_condition,omitempty"`
	Examination          *string           `json:"examination,omitempty"`
	Diagnosis            *string           `json:"diagnosis,omitempty"`
	Intervention         *string           `json:"intervention,omitempty"`
	PlanningAndEducation *string           `json:"planning_and_education,omitempty"`
	CreatedAt            time.Time         `json:"created_at"`
	UpdatedAt            time.Time         `json:"updated_at"`
	TreatmentSession     *TreatmentSession `json:"treatment_session"`
}

type TreatmentSessionReportConnection struct {
	Nodes      []*TreatmentSessionReport `json:"nodes"`
	TotalCount int32                     `json:"total_count"`
}

type UpdatePatientInput struct {
	FullName         *string                `json:"full_name,omitempty"`
	Phone            *string                `json:"phone,omitempty"`
	Email            *string                `json:"email,omitempty"`
	Address          *string                `json:"address,omitempty"`
	EmergencyContact *EmergencyContactInput `json:"emergency_contact,omitempty"`
}

type UpdateStaffInput struct {
	FullName       *string `json:"full_name,omitempty"`
	Specialization *string `json:"specialization,omitempty"`
	LicenseNo      *string `json:"license_no,omitempty"`
	Phone          *string `json:"phone,omitempty"`
}

type UpdateTreatmentSessionReportInput struct {
	Anamnesis            *string `json:"anamnesis,omitempty"`
	MechanismOfInjury    *string `json:"mechanism_of_injury,omitempty"`
	ActualCondition      *string `json:"actual_condition,omitempty"`
	Examination          *string `json:"examination,omitempty"`
	Diagnosis            *string `json:"diagnosis,omitempty"`
	Intervention         *string `json:"intervention,omitempty"`
	PlanningAndEducation *string `json:"planning_and_education,omitempty"`
}

type UpdateTreatmentSessionStatusInput struct {
	Status SessionStatus `json:"status"`
}

type UpdateUserInput struct {
	Email    *string   `json:"email,omitempty"`
	Password *string   `json:"password,omitempty"`
	Role     *UserRole `json:"role,omitempty"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Role      UserRole  `json:"role"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Staff     *Staff    `json:"staff,omitempty"`
}

type Gender string

const (
	GenderMale   Gender = "MALE"
	GenderFemale Gender = "FEMALE"
)

var AllGender = []Gender{
	GenderMale,
	GenderFemale,
}

func (e Gender) IsValid() bool {
	switch e {
	case GenderMale, GenderFemale:
		return true
	}
	return false
}

func (e Gender) String() string {
	return string(e)
}

func (e *Gender) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Gender(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Gender", str)
	}
	return nil
}

func (e Gender) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Gender) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Gender) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SessionStatus string

const (
	SessionStatusScheduled  SessionStatus = "SCHEDULED"
	SessionStatusInProgress SessionStatus = "IN_PROGRESS"
	SessionStatusCompleted  SessionStatus = "COMPLETED"
	SessionStatusCancelled  SessionStatus = "CANCELLED"
)

var AllSessionStatus = []SessionStatus{
	SessionStatusScheduled,
	SessionStatusInProgress,
	SessionStatusCompleted,
	SessionStatusCancelled,
}

func (e SessionStatus) IsValid() bool {
	switch e {
	case SessionStatusScheduled, SessionStatusInProgress, SessionStatusCompleted, SessionStatusCancelled:
		return true
	}
	return false
}

func (e SessionStatus) String() string {
	return string(e)
}

func (e *SessionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SessionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SessionStatus", str)
	}
	return nil
}

func (e SessionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SessionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SessionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRoleAdmin        UserRole = "ADMIN"
	UserRoleTherapist    UserRole = "THERAPIST"
	UserRoleReceptionist UserRole = "RECEPTIONIST"
)

var AllUserRole = []UserRole{
	UserRoleAdmin,
	UserRoleTherapist,
	UserRoleReceptionist,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleAdmin, UserRoleTherapist, UserRoleReceptionist:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
