package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/arganaphang/cycle/backend/graph/model"
	"github.com/google/uuid"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// CreateStaff is the resolver for the createStaff field.
func (r *mutationResolver) CreateStaff(ctx context.Context, input model.CreateStaffInput) (*model.Staff, error) {
	panic(fmt.Errorf("not implemented: CreateStaff - createStaff"))
}

// CreatePatient is the resolver for the createPatient field.
func (r *mutationResolver) CreatePatient(ctx context.Context, input model.CreatePatientInput) (*model.Patient, error) {
	panic(fmt.Errorf("not implemented: CreatePatient - createPatient"))
}

// UpdatePatient is the resolver for the updatePatient field.
func (r *mutationResolver) UpdatePatient(ctx context.Context, id uuid.UUID, input model.UpdatePatientInput) (*model.Patient, error) {
	panic(fmt.Errorf("not implemented: UpdatePatient - updatePatient"))
}

// CreateAppointment is the resolver for the createAppointment field.
func (r *mutationResolver) CreateAppointment(ctx context.Context, input model.CreateAppointmentInput) (*model.Appointment, error) {
	panic(fmt.Errorf("not implemented: CreateAppointment - createAppointment"))
}

// UpdateAppointmentStatus is the resolver for the updateAppointmentStatus field.
func (r *mutationResolver) UpdateAppointmentStatus(ctx context.Context, id uuid.UUID, input model.UpdateAppointmentStatusInput) (*model.Appointment, error) {
	panic(fmt.Errorf("not implemented: UpdateAppointmentStatus - updateAppointmentStatus"))
}

// CancelAppointment is the resolver for the cancelAppointment field.
func (r *mutationResolver) CancelAppointment(ctx context.Context, id uuid.UUID) (*model.Appointment, error) {
	panic(fmt.Errorf("not implemented: CancelAppointment - cancelAppointment"))
}

// CreateSession is the resolver for the createSession field.
func (r *mutationResolver) CreateSession(ctx context.Context, input model.CreateSessionInput) (*model.TreatmentSession, error) {
	panic(fmt.Errorf("not implemented: CreateSession - createSession"))
}

// CompleteSession is the resolver for the completeSession field.
func (r *mutationResolver) CompleteSession(ctx context.Context, id uuid.UUID) (*model.TreatmentSession, error) {
	panic(fmt.Errorf("not implemented: CompleteSession - completeSession"))
}

// CancelSession is the resolver for the cancelSession field.
func (r *mutationResolver) CancelSession(ctx context.Context, id uuid.UUID) (*model.TreatmentSession, error) {
	panic(fmt.Errorf("not implemented: CancelSession - cancelSession"))
}

// CreateSOAPNote is the resolver for the createSOAPNote field.
func (r *mutationResolver) CreateSOAPNote(ctx context.Context, input model.CreateSOAPNoteInput) (*model.SOAPNote, error) {
	panic(fmt.Errorf("not implemented: CreateSOAPNote - createSOAPNote"))
}

// UpdateSOAPNote is the resolver for the updateSOAPNote field.
func (r *mutationResolver) UpdateSOAPNote(ctx context.Context, id uuid.UUID, input model.UpdateSOAPNoteInput) (*model.SOAPNote, error) {
	panic(fmt.Errorf("not implemented: UpdateSOAPNote - updateSOAPNote"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Patient is the resolver for the patient field.
func (r *queryResolver) Patient(ctx context.Context, id uuid.UUID) (*model.Patient, error) {
	panic(fmt.Errorf("not implemented: Patient - patient"))
}

// Patients is the resolver for the patients field.
func (r *queryResolver) Patients(ctx context.Context, search *string, limit *int32, offset *int32) (*model.PatientConnection, error) {
	panic(fmt.Errorf("not implemented: Patients - patients"))
}

// Staff is the resolver for the staff field.
func (r *queryResolver) Staff(ctx context.Context, id uuid.UUID) (*model.Staff, error) {
	panic(fmt.Errorf("not implemented: Staff - staff"))
}

// AllStaff is the resolver for the allStaff field.
func (r *queryResolver) AllStaff(ctx context.Context, search *string, limit *int32, offset *int32) (*model.StaffConnection, error) {
	panic(fmt.Errorf("not implemented: AllStaff - allStaff"))
}

// Appointment is the resolver for the appointment field.
func (r *queryResolver) Appointment(ctx context.Context, id uuid.UUID) (*model.Appointment, error) {
	panic(fmt.Errorf("not implemented: Appointment - appointment"))
}

// Appointments is the resolver for the appointments field.
func (r *queryResolver) Appointments(ctx context.Context, filter *model.AppointmentFilter, limit *int32, offset *int32) (*model.AppointmentConnection, error) {
	panic(fmt.Errorf("not implemented: Appointments - appointments"))
}

// TreatmentSession is the resolver for the treatmentSession field.
func (r *queryResolver) TreatmentSession(ctx context.Context, id uuid.UUID) (*model.TreatmentSession, error) {
	panic(fmt.Errorf("not implemented: TreatmentSession - treatmentSession"))
}

// TreatmentSessions is the resolver for the treatmentSessions field.
func (r *queryResolver) TreatmentSessions(ctx context.Context, filter *model.SessionFilter, limit *int32, offset *int32) (*model.TreatmentSessionConnection, error) {
	panic(fmt.Errorf("not implemented: TreatmentSessions - treatmentSessions"))
}

// SoapNote is the resolver for the soapNote field.
func (r *queryResolver) SoapNote(ctx context.Context, sessionID uuid.UUID) (*model.SOAPNote, error) {
	panic(fmt.Errorf("not implemented: SoapNote - soapNote"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
