package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"net/http"
	"time"

	"github.com/arganaphang/cycle/backend/graph/model"
	"github.com/google/uuid"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	result, err := r.Services.UserService.Login(ctx, input)
	if err != nil {
		return nil, err
	}

	// ? Set Cookie
	hr := ForHttpContext(ctx)
	if hr == nil {
		return nil, errors.New("failed to get http context")
	}

	cookie := &http.Cookie{
		Name:     "auth_token",
		Value:    result.Token,
		HttpOnly: true,
		Expires:  time.Now().Add((time.Hour * 24 * 30) - time.Second),
	}

	http.SetCookie(hr, cookie)

	return result, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	return r.Services.UserService.Create(ctx, input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id uuid.UUID, input model.UpdateUserInput) (*model.User, error) {
	return r.Services.UserService.Update(ctx, id, input)
}

// CreateStaff is the resolver for the createStaff field.
func (r *mutationResolver) CreateStaff(ctx context.Context, input model.CreateStaffInput) (*model.Staff, error) {
	return r.Services.StaffService.Create(ctx, input)
}

// UpdateStaff is the resolver for the updateStaff field.
func (r *mutationResolver) UpdateStaff(ctx context.Context, id uuid.UUID, input model.UpdateStaffInput) (*model.Staff, error) {
	return r.Services.StaffService.Update(ctx, id, input)
}

// CreatePatient is the resolver for the createPatient field.
func (r *mutationResolver) CreatePatient(ctx context.Context, input model.CreatePatientInput) (*model.Patient, error) {
	return r.Services.PatientService.Create(ctx, input)
}

// UpdatePatient is the resolver for the updatePatient field.
func (r *mutationResolver) UpdatePatient(ctx context.Context, id uuid.UUID, input model.UpdatePatientInput) (*model.Patient, error) {
	return r.Services.PatientService.Update(ctx, id, input)
}

// CreateTreatmentSession is the resolver for the createTreatmentSession field.
func (r *mutationResolver) CreateTreatmentSession(ctx context.Context, input model.CreateTreatmentSessionInput) (*model.TreatmentSession, error) {
	return r.Services.TreatmentSessionService.Create(ctx, input)
}

// UpdateTreatmentSessionStatus is the resolver for the updateTreatmentSessionStatus field.
func (r *mutationResolver) UpdateTreatmentSessionStatus(ctx context.Context, id uuid.UUID, input model.UpdateTreatmentSessionStatusInput) (*model.TreatmentSession, error) {
	return r.Services.TreatmentSessionService.UpdateStatus(ctx, id, input.Status)
}

// CreateTreatmentSessionReport is the resolver for the createTreatmentSessionReport field.
func (r *mutationResolver) CreateTreatmentSessionReport(ctx context.Context, input model.CreateTreatmentSessionReportInput) (*model.TreatmentSessionReport, error) {
	return r.Services.TreatmentSessionReportService.Create(ctx, input)
}

// UpdateTreatmentSessionReport is the resolver for the updateTreatmentSessionReport field.
func (r *mutationResolver) UpdateTreatmentSessionReport(ctx context.Context, id uuid.UUID, input model.UpdateTreatmentSessionReportInput) (*model.TreatmentSessionReport, error) {
	return r.Services.TreatmentSessionReportService.Update(ctx, id, input)
}

// TreatmentSessions is the resolver for the treatment_sessions field.
func (r *patientResolver) TreatmentSessions(ctx context.Context, obj *model.Patient) ([]*model.TreatmentSession, error) {
	return GetTreatmentSessionByPatientID(ctx, obj.ID)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	auth := ForAuthContext(ctx)
	if auth == nil {
		return nil, errors.New("failed to get auth context")
	}
	return r.Services.UserService.FindByID(ctx, auth.ID)
}

// Patient is the resolver for the patient field.
func (r *queryResolver) Patient(ctx context.Context, id uuid.UUID) (*model.Patient, error) {
	return r.Services.PatientService.FindByID(ctx, id)
}

// Patients is the resolver for the patients field.
func (r *queryResolver) Patients(ctx context.Context, search *string, limit *int32, offset *int32) (*model.PatientConnection, error) {
	return r.Services.PatientService.FindAll(ctx, search, limit, offset)
}

// Staff is the resolver for the staff field.
func (r *queryResolver) Staff(ctx context.Context, id uuid.UUID) (*model.Staff, error) {
	return r.Services.StaffService.FindByID(ctx, id)
}

// Staffs is the resolver for the staffs field.
func (r *queryResolver) Staffs(ctx context.Context, search *string, limit *int32, offset *int32) (*model.StaffConnection, error) {
	return r.Services.StaffService.FindAll(ctx, search, limit, offset)
}

// TreatmentSession is the resolver for the treatmentSession field.
func (r *queryResolver) TreatmentSession(ctx context.Context, id uuid.UUID) (*model.TreatmentSession, error) {
	return r.Services.TreatmentSessionService.FindByID(ctx, id)
}

// TreatmentSessions is the resolver for the treatmentSessions field.
func (r *queryResolver) TreatmentSessions(ctx context.Context, filter *model.SessionFilter, limit *int32, offset *int32) (*model.TreatmentSessionConnection, error) {
	return r.Services.TreatmentSessionService.FindAll(ctx, filter, limit, offset)
}

// TreatmentSessionReport is the resolver for the treatmentSessionReport field.
func (r *queryResolver) TreatmentSessionReport(ctx context.Context, id uuid.UUID) (*model.TreatmentSessionReport, error) {
	return r.Services.TreatmentSessionReportService.FindByID(ctx, id)
}

// TreatmentSessionReports is the resolver for the treatmentSessionReports field.
func (r *queryResolver) TreatmentSessionReports(ctx context.Context, filter *model.ReportFilter, limit *int32, offset *int32) (*model.TreatmentSessionReportConnection, error) {
	return r.Services.TreatmentSessionReportService.FindAll(ctx, filter, limit, offset)
}

// User is the resolver for the user field.
func (r *staffResolver) User(ctx context.Context, obj *model.Staff) (*model.User, error) {
	return GetUser(ctx, obj.UserID)
}

// Patient is the resolver for the patient field.
func (r *treatmentSessionResolver) Patient(ctx context.Context, obj *model.TreatmentSession) (*model.Patient, error) {
	return GetPatient(ctx, obj.PatientID)
}

// Staff is the resolver for the staff field.
func (r *treatmentSessionResolver) Staff(ctx context.Context, obj *model.TreatmentSession) (*model.Staff, error) {
	return GetStaff(ctx, obj.StaffID)
}

// Report is the resolver for the report field.
func (r *treatmentSessionResolver) Report(ctx context.Context, obj *model.TreatmentSession) (*model.TreatmentSessionReport, error) {
	return GetReportBySessionID(ctx, obj.ID)
}

// Staff is the resolver for the staff field.
func (r *userResolver) Staff(ctx context.Context, obj *model.User) (*model.Staff, error) {
	return GetStaffByUserID(ctx, obj.ID)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Patient returns PatientResolver implementation.
func (r *Resolver) Patient() PatientResolver { return &patientResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Staff returns StaffResolver implementation.
func (r *Resolver) Staff() StaffResolver { return &staffResolver{r} }

// TreatmentSession returns TreatmentSessionResolver implementation.
func (r *Resolver) TreatmentSession() TreatmentSessionResolver { return &treatmentSessionResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type patientResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type staffResolver struct{ *Resolver }
type treatmentSessionResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
